apiVersion: aws.platform.upbound.io/v1alpha1
kind: XAWSLBController
metadata:
  name: configuration-aws-lb-controller
  annotations:
    render.crossplane.io/composition-path: apis/pat/composition.yaml
    render.crossplane.io/function-path: examples/functions.yaml
    uptest.upbound.io/post-delete-hook: post_delete.sh
  labels:
    platform.upbound.io/deletion-ordering: enabled
spec:
  parameters:
    region: eu-central-1
    helm:
      providerConfigName: configuration-aws-lb-controller
    clusterNameSelector:
      matchLabels:
        crossplane.io/composite: configuration-aws-lb-controller
