apiVersion: aws.platform.upbound.io/v1alpha1
kind: AWSLBController
metadata:
  name: aws-load-balancer-controller
  namespace: default
  labels:
    platform.upbound.io/deletion-ordering: enabled
spec:
  compositeDeletePolicy: Foreground
  parameters:
    clusterName: platform-ref-aws-7b49p-tfghv
    providerConfigName: platform-ref-aws
