apiVersion: aws.platform.upbound.io/v1alpha1
kind: XEKS
metadata:
  name: configuration-aws-lb-controller
  labels:
    platform.upbound.io/deletion-ordering: enabled
spec:
  parameters:
    id: configuration-aws-lb-controller
    region: eu-west-1
    version: "1.27"
    #iam:
      # replace with your custom arn like:
      # principalArn: arn:aws:iam::123456789:role/AWSReservedSSO_AdministratorAccess_d703c73ed340fde7
    nodes:
      count: 3
      instanceType: t3.small
  writeConnectionSecretToRef:
    name: configuration-aws-lb-controller
    namespace: upbound-system
