apiVersion: aws.platform.upbound.io/v1alpha1
kind: XNetwork
metadata:
  name: configuration-aws-lb-controller
spec:
  parameters:
    id: configuration-aws-lb-controller
    region: eu-central-1
    subnets:
      - availabilityZone: eu-central-1a
        type: public
        cidrBlock: 192.168.0.0/18
      - availabilityZone: eu-central-1b
        type: public
        cidrBlock: 192.168.64.0/18
      - availabilityZone: eu-central-1a
        type: private
        cidrBlock: 192.168.128.0/18
      - availabilityZone: eu-central-1b
        type: private
        cidrBlock: 192.168.192.0/18
